%% Insert minimal data on the right side
filename =             filename; %Metadata YAML filename
description =          description;
num_pixels =           num_pixels;
num_spots =            num_spots;
num_spectral_ch =      num_spectral_ch;
num_split_ch =         num_split_ch;
modulated_excitation = modulated_excitation;
if modulated_excitation
    modulated_excitation = 'True';
else
    modulated_excitation = 'False';
end
lifetime =             lifetime;
if lifetime
    lifetime = 'True';
else
    lifetime = 'False';
end
timestamps_unit =      timestamps_unit;

%% Format into YAML form

formatSpec = ['description: %s \n'...
'\n'...
'setup: \n'...
'    num_pixels: %hd                # number single-pixel detectors \n'...
'    num_spots: %hd                 # number of confocal excitation spots \n'...
'    num_spectral_ch: %hd           # 2 for donor and acceptor detection \n'...
'    num_polarization_ch: %hd       # 1 = no polarization selection \n'...
'    num_split_ch: %hd              # 1 = no beam splitting \n'...
'    modulated_excitation: %s   # CW excitation, no modulation \n'...
'    lifetime: %s               # no TCSPC in detection \n'...
'\n'...
'photon_data: \n'...
'    timestamps_specs: \n'...
'        timestamps_unit: %g   # 10 ns'];


%% Write to YAML file
fileID = fopen(filename,'w');
fprintf(fileID,formatSpec,description,num_pixels,num_spots,num_spectral_ch,...
        num_polarization_ch,num_split_ch,modulated_excitation,lifetime,...
        timestamps_unit);
fclose(fileID);